#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

apt-get update
apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

nginx -t

service nginx restart
