#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string

apt-get update
apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html
new_string="listen 80 default_server;\\n\\tlocation \/redirect_me {\\n\\t\\treturn 301 https:\/\/www.youtube.com\/watch?v=xJJsoquu70o\/;\\n\\t}"
sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
second_string="listen 80 default_server;\\nerror_page 404 \/404.html;\\n\\tlocation = \/404.html {\\n\\t\\troot \/var\/www\/html;\\n\\t\\tinternal;\\n\\t}"
sed -i "s/listen 80 default_server;/$second_string/" /etc/nginx/sites-available/default

service nginx start
