#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 10000
    timeout server 10000

listen load_balancer
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 931-web-01 35.185.103.0:80 check
    server 931-web-02 35.237.21.105:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
