#!/usr/bin/env bash
# Bash script with multiple executions

echo "$$" > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 0.5
done