#!/usr/bin/env bash
# Print a clock from Hour 0-12 and Min 1-59

hour="0"
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	min="1"
	while [ $min -le 59 ]
	do
		echo "$min"
		(( min++ ))
	done
	(( hour++ ))
done