#!/usr/bin/env bash
# Script that gives information of a empty or non empty file

if [ -e "holbertonschool" ]
then
	echo "holbertonschool file exists"
	if [ -s "holbertonschool" ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi

	if [ -f "holbertonschool" ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi