#!/usr/bin/env bash
# Run Nginx as Nginx
sed -i "s/#user www-data/user ngnix/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
