#!/usr/bin/env bash
# Run Nginx as Nginx
sed -i "s/#user www-data/user ngix/" /etc/nginx/nginx.conf
sed -i -E "s/(listen *)80 /\18080 /g"/etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
